ai_chat/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("chat.urls")),
    path('api/', include('rest_framework.urls')),
    
]

if settings.DEBUG:
	urlpatterns.append(path('static/<path:path>', never_cache(serve)))

chat/urls.py
from django.urls import include, path, re_path
from chat import views
from .views import BBLoginView, BBLogoutView

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('chat/', views.chat_home),
    #path('chat/gpt/', views.gpt_response, name= 'my_chat_gpt'),
    path('chat/gpt/', views.chat_page, name= 'my_chat_gpt'),
    path('chat/gpt/<int:id>', views.chat_page, name= 'my_chat_gpt_id'),
    path('chat/gpt/instruction/chat/', views.chat_instruction, name= 'my_chat_gpt_instruction'),
    path('chat/gpt/instruction/prop/', views.prop_instruction, name= 'my_prop_gpt_instruction'),
    
    path('chat/db/', views.load_base_page, name= 'my_load_base'),
    path('chat/db/web', views.load_web_page, name= 'my_load_web'),
    path('chat/db/embedding/chat', views.create_chat_embedding_page, name= 'my_create_chat_embedding'),
    path('chat/db/embedding/prop', views.create_prop_embedding_page, name= 'my_create_prop_embedding'),
    path('chat/db/chat', views.load_chat_data_page, name= 'my_load_chat'),
    
    path('chat/db/train/', views.train_page, name= 'my_train_model'),
    
    path('chat/db/train/status/', views.train_status_page, name= 'my_status_model'),
    path('chat/db/new/<int:id>/', views.new_em_proposal_page, name= 'my_new_proposal'),
    path('chat/db/new/', views.new_em_proposal_page, name= 'my_new_proposal'),
    path('chat/db/edit/<int:id>/', views.edit_em_proposal_page, name= 'my_edit_proposal'),
    path('chat/db/edit/', views.edit_em_proposal_page, name= 'my_edit_proposal'),
    
    path('chat/db/edit/del/<int:id>/', views.delete_record_edit, name= 'my_del_record_edit'),
    path('chat/db/new/del/<int:id>/', views.delete_record_new, name= 'my_del_record_new'),
    path('chat/gpt/del/<int:id>/', views.delete_chat, name= 'my_del_chat'),
    
    
    path('accounts/register/activate/<str:sign>/', views.user_activate, name= 'my_register_activate'),
    path('accounts/register/done/', views.RegisterDoneView.as_view(), name= 'my_register_done'),
    path('accounts/register/', views.RegisterUserView.as_view(), name= 'my_register'),
    path('accounts/profile/delete/', views.DeleteUserView.as_view(), name= 'my_profile_delete'),
    path('accounts/profile/change/', views.ChangeUserInfoView.as_view(), name= 'my_profile_change'),
    path('accounts/profile/', views.user_profile, name= 'my_profile'),
    path('accounts/login/', BBLoginView.as_view(), name= 'my_login'),
    path('accounts/logout/', BBLogoutView.as_view(), name= 'my_logout'),
    path('accounts/password/change/', views.BBPasswordChangeView.as_view(), name= 'my_password_change'),
    path('<str:page>/', views.other_page, name= 'other'),
    
    
    path('m400', views.m400),
    
     
]

chat/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

version = 3.3

class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default = True, db_index = True, verbose_name = 'Has been activated ?')
    send_messages = models.BooleanField(default = True, verbose_name = 'Send update messages ?')
    paid_account = models.BooleanField(default = False)
    
    class Meta(AbstractUser.Meta):
        pass

class ChatList(models.Model):
    owner = models.ForeignKey(AdvUser, verbose_name='Chat owner.', on_delete = models.DO_NOTHING)
    chat_name = models.CharField(max_length=100)
    
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Message time.')
    chat_type = models.CharField(max_length=30, default = 'none')
    company = models.CharField(max_length=100, default = 'none')
    subject = models.CharField(max_length=100, default = 'none')
    status = models.CharField(max_length=30, default = 'open')

    def __str__(self):
        return f"ChatName: {self.chat_name}"

    @classmethod
    def get_all_messages(cls):
        return cls.objects.all()    
        
class MessageChain(models.Model):
    owner = models.ForeignKey(AdvUser, verbose_name='Chein owner.', on_delete = models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Message time.')
    job_title = models.TextField(default = "noname")
    job_description = models.TextField()
    proposal_cover_letter = models.TextField()
    chat_interview = models.TextField()

    def __str__(self):
        return f"MessageChain: {self.id}"
    
class QuestionAnswer(models.Model):
    message_chain = models.ForeignKey(MessageChain, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Message time.')
    question = models.TextField()
    answer = models.TextField()

    def __str__(self):
        return f"QuestionAnswer: {self.question} - {self.answer}"
        
class ProposalHistory(models.Model):
    message_chain = models.ForeignKey(MessageChain, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Message time.')
    user_question = models.TextField()
    ai_answer = models.TextField()

    def __str__(self):
        return f"ProposalHistory: {self.user_question} - {self.ai_answer}"
        
class ChatHistory(models.Model):
    message = models.ForeignKey(ChatList, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Message time.')
    user_question = models.TextField()
    ai_answer = models.TextField()

    def __str__(self):
        return f"ChatHistory: {self.user_question} - {self.ai_answer}"

chat/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.base import TemplateView

from django.core.signing import BadSignature
from django.utils.encoding import smart_str
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, HttpResponseBadRequest, Http404

from .forms import *
from .models import *
from .utilities import signer, load_from_xls
from .ai_train import *

import pandas as pd
import openai
import requests
from dotenv import load_dotenv
import os
from .ai_embedding import *


class BBLoginView(LoginView):
    template_name = 'chat/chat_login.html'
    
class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'chat/chat_logout.html'

class RegisterDoneView(TemplateView):
    template_name = 'chat/chat_register_done.html'
    
class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'chat/chat_register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('chat:my_register_done')

class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'chat/chat_change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('chat:my_profile')
    success_message = 'User data changed'
    
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)
    
class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'chat/chat_password_change.html'
    success_url = reverse_lazy('chat:my_profile')
    success_message = 'User password changed'
    
class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'chat/chat_delete_user.html'
    success_url = reverse_lazy('chat:index')
    
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'User deleted')
        return super().post(request, *args, **kwargs)
    
    def get_object(self, queryset = None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk = self.user_id)
    
def index(request):   
    content = 'The homepage of AI Chat.'
    context = {"content": content}
    return render(request, "index.html", context)

@login_required
def user_profile(request):
    return render(request, 'chat/chat_profile.html')

def user_activate(request, sign):
    try:
        
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'chat/chat_bad_signature.html')
    
    user = get_object_or_404(AdvUser, username = username)
    if user.is_activated:
        template = 'chat/chat_user_is_activated.html'
    else:
        template = 'chat/chat_activation_done.html'
        user.is_active = True
        user.is_activated = True
        user.save()
    return render(request, template)# Create your views here.

@login_required
def create_chat_embedding_page(request):

    f_name = "train_data_ask.jsonl"
    # папка базы данных
    persist_directory = 'chat/db/CrisEmbeddingsChat/'
    # путь к учебным материалам
    data_directory = 'chat/db/Cris/'
    #"chat/train_data_ask.jsonl"
    system_doc = 'support_instruction.txt'
    
    if request.method == "POST":
        userform = DbLoadForm(request.POST or None)
        if userform.is_valid():
            f_name = userform.cleaned_data["db_name"]
            gptLearning = WorkerОpenAI(data_directory + system_doc, persist_directory)
    
            # # Подготовка эмбедингов
            gptLearning.create_embedding(data_directory + f_name, # путь к учебным материалам
                                        persist_directory) # путь для сохранения базы данных
        
    parts = DbLoadForm(initial= {"db_name":f_name})
    template = 'chat/chat_create_embedding.html'
    
    context = {"form": parts, "user_name":request.user}
    return render(request, template, context)
    
@login_required
def create_prop_embedding_page(request):

    #f_name = "train_data_ask.jsonl"
    # папка базы данных
    #persist_directory = 'chat/db/MagicVap'
    persist_directory = 'chat/db/MagicVap'
    # путь к учебным материалам
    #data_directory = 'chat/db/MagicVap/'
    data_directory = 'chat/db/MagicVap/'
    #"chat/train_data_ask.jsonl"
    #system_doc = 'support_instruction.txt'
    company_dir = 'Maxximize/'
    #gptLearning = WorkerОpenAIProposal(WorkerОpenAIProposal.data_directory_prop + 'train_data_jobs.jsonl', WorkerОpenAIProposal.persist_directory_prop)
    gptLearning = WorkerОpenAIProposal('', company_dir)
    #gptLearning.db_proposal_file = 'train_data_jobs.jsonl'
    gptLearning.db_proposal_file = '*.*'
    
    if request.method == "POST":
        userform = DbLoadForm(request.POST or None)
        if userform.is_valid():
            f_name = userform.cleaned_data["db_name"]
            
    
            # # Подготовка эмбедингов
            gptLearning.create_embedding(gptLearning.data_directory, # путь к учебным материалам
                                        gptLearning.persist_directory) # путь для сохранения базы данных
        
    parts = DbLoadForm(initial= {"db_name":gptLearning.db_proposal_file})
    template = 'chat/chat_create_embedding.html'
    
    context = {"form": parts, "user_name":request.user}
    return render(request, template, context)
    
@login_required
def load_chat_data_page(request):

    f_name = "train_data_ask.jsonl"
    if request.method == "POST":
        userform = DbLoadForm(request.POST or None)
        if userform.is_valid():
            f_name = userform.cleaned_data["db_name"]
            load_from_xls(f_name, request.user)
    parts = DbLoadForm(initial= {"db_name":f_name})
    template = 'chat/chat_load_chat_base.html'
    chain_list = MessageChain.objects.filter(owner=request.user)

    context = {"form": parts, "tests_log": chain_list, "user_name":request.user}
    return render(request, template, context)

@login_required
def load_base_page(request):
    f_name = "chat/upwork_list.xlsx"
    if request.method == "POST":
        userform = DbLoadForm(request.POST or None)
        if userform.is_valid():
            f_name = userform.cleaned_data["db_name"]
            load_from_xls(f_name, request.user)
    parts = DbLoadForm(initial= {"db_name":f_name})
    template = 'chat/chat_load_base.html'
    chain_list = MessageChain.objects.filter(owner=request.user)
#    tests_list = AllBackTests.objects.all()
#    tests_list.delete()
#    tests_list = AllBackTests.objects.all()
    context = {"form": parts, "tests_log": chain_list, "user_name":request.user}
    return render(request, template, context)

def load_web_page(request):
    res_f_name = 'magicvaporizers.txt'
    my_url = "https://magicvaporizers.co.uk"
    
    scrape_site(my_url, res_f_name)
    
# Функция для обработки формы диалога
def gpt_response(request):
    # Получаем ответ от ChatGPT
    query = "Extract the name and mailing address from this email:\n\nDear Kelly,\n\nIt was great to talk to you at the seminar. I thought Jane's talk was quite good.\n\nThank you for the book. Here's my address 2111 Ash Lane, Crestview CA 92002\n\nBest,\n\nMaya\n\nName:" 
    #"Name all the presidents of the USA"
    response = get_response("text-davinci-003", query)
    

    # Отправляем ответ пользователю
    context = {"question": query, "gpt_response": response, "user_name":request.user}
    return render(request, "chat/chat_gpt_response.html", context)
    
    
def train_page(request):
    #train_chat()
    create_train_file()
    context = {"train_res": "Training of model complited!"}
    return render(request, "chat/chat_train_model.html", context)
    
def train_status_page(request):
    response = "No treined models"
    #response = train_status("ft-7QqiAyTvtmME8WHn6ZKAQa07")
    parts = OutTextForm(initial= {"f_content":response})
    context = {"form": parts}
    return render(request, "chat/chat_train_status.html", context)

def other_page(request, page):
    try:
        template = get_template('chat/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request = request))

def chat_home(request):
    data = {"header": "Main window", "message": "Welcome to Chat!"}
    return render(request, "chat/chat_home.html", context=data)
    
# delete record
def delete_record_new(request, id):
    try:
        test = MessageChain.objects.get(id=id)
        test.delete()
        return redirect('chat:my_new_proposal')
    except MessageChain.DoesNotExist:
        template = 'chat/chat_msg_page.html'
        context = {"my_msg":"<h2>Record not found</h2>"}
        return render(request, template, context)

# delete record
def delete_record_edit(request, id):
    try:
        test = MessageChain.objects.get(id=id)
        test.delete()
        return redirect('chat:my_edit_proposal')
    except MessageChain.DoesNotExist:
        template = 'chat/chat_msg_page.html'

chat/templates/chat/chat_bad_signature.html
{% extends "chat/chat_base.html" %}

{% block title %} Activation error {% endblock %}

{% block content %}
<h2> Activation </h2>
<p> Activation of a user with this name failed! </p>
<p> <a href="{% url chat:my_register %}"> Register again </a> </p>
{% endblock %}

chat/templates/chat/chat_base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
      	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>{% block title %}Chat{% endblock %} - ai </title>
      	<!-- Bootstrap CSS --
		<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
      <!-- -->
		{% bootstrap_css %}
      	<link rel= "stylesheet" type= "text/css" href= "{% static 'my_css/chat_style.css' %}">
		{% bootstrap_javascript jquery='slim' %}
	</head>
  	<body class= "container-fluid">
		<!-- JQuery -->
		<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
		
		
		<header class= "mb-4">
          <h1 class= "display-1 text-center"> Ai Chat </h1>
		</header>
		<div class="row border" >
          	<ul class="col nav justify-content-start ">
              <li class="nav-item root"><a class="nav-link" href="{% url 'chat:index' %}">Home</a></li>
              <li class="nav-item root"><a class= "nav-link" href= "{% url 'chat:other' page='chat_about' %}"> About </a></li>
              
          	</ul>
			<ul class="col nav justify-content-end ">
				{% if user.is_authenticated %}
              	<li class= "nav-item dropdown">
                	<a class= "nav-link dropdown-toggle" data-toggle= "dropdown" href= "#" role= "button" aria-haspopup= "true" aria-expanded= "false"> Profile </a>
				
					<div class="dropdown-menu">
                      <a class= "dropdown-item" href= "{% url 'chat:my_profile' %}"> User </a>
                      <a class= "dropdown-item" href= "{% url 'chat:my_profile_change' %}"> Change personal data </a>
                      <a class= "dropdown-item" href= "{% url 'chat:my_password_change' %}"> Change password </a>
                      <div class= "dropdown-divider"></div>
                      <a class= "dropdown-item" href= "{% url 'chat:my_logout' %}"> Logout </a>
                      <div class= "dropdown-divider"></div>
                      <a class= "dropdown-item" href= "{% url 'chat:my_profile_delete' %}"> Delete </a>
					
					</div>
				</li>
              	{% else %}
              	<li class="nav-item"><a class="nav-link" href= "{% url 'chat:my_login' %}"> Login </a></li>
              	{% endif %}
              	<li class="nav-item"><a class="nav-link" href="{% url 'chat:my_register' %}">Register</a></li>
              	
			</ul>
		</div>
      	<div class= "row">
          <nav class= "col-md-auto nav flex-column border">
            {% if user.is_authenticated %}
            <li class="nav-item root"><a class="nav-link" href="{% url 'chat:my_chat_gpt' %}">Chat</a></li>
			<li class="nav-item root"><a class="nav-link" href="{% url 'chat:my_chat_gpt_instruction' %}">Set chat instruction</a></li>
			<li class="nav-item root"><a class="nav-link" href="{% url 'chat:my_prop_gpt_instruction' %}">Set prop instruction</a></li>
			            
            <span class= "nav-link root font-weight-bold"> Data base </span>
            	<ul>
					<li class="nav-item root"><a class="nav-link" href="{% url 'chat:my_new_proposal' %}">New proposal</a></li>
					<li class="nav-item root"><a class="nav-link" href="{% url 'chat:my_edit_proposal' id='0' %}">Edit proposal</a></li>
					
					{% if user.is_superuser %}
					<li class="nav-item root"><a class="nav-link" href="{% url 'chat:my_load_base' %}">Load data base</a></li>
					<li class="nav-item root"><a class="nav-link" href="{% url 'chat:my_load_web' %}">Load WEB</a></li>
					<li class="nav-item root"><a class="nav-link" href="{% url 'chat:my_create_chat_embedding' %}">Create chat embedding</a></li>
					<li class="nav-item root"><a class="nav-link" href="{% url 'chat:my_create_prop_embedding' %}">Create prop embedding</a></li>
					<li class="nav-item root"><a class="nav-link" href= "{% url 'chat:my_train_model' %}"> Train model </a></li>
					<li class="nav-item root"><a class="nav-link" href= "{% url 'chat:my_status_model' %}"> Training status </a></li>
					{% endif %}
            		<a class= "nav-link" href= "{% url 'chat:other' page='#' %}"> Other </a>
           	 		
            	</ul>  
            {% endif %}
                        
          </nav>
          <section class= "col border py-2">
            
			
            {% block content %}
            {% endblock content%}
          </section>
      	</div>
		<footer class="mt-3">
			<p class="text-right font-italic"> v3.4  &copy; Murd.</p>
		</footer>
		

		
	</body>
</html>  

chat/templates/chat/chat_create_embedding.html
{% extends "chat/chat_base.html" %}

{% load static %}
{% load bootstrap4 %}

{% block title %} Create embeddings {% endblock %}

{% block content %}
<h2> Load data base </h2>
<div class="conteiner-fluid mb-2 border">
<form name="Load data base" method="POST" >
  {% csrf_token %}
  <div class="row mb-2">
    
	<div class="col">
		<div class="row">&nbsp</div>
		<div class="row ml-4">
			{{ form.db_name.label_tag }}
		</div>
		<div class="row ml-4">
			{{ form.db_name }}<br>
		</div>
		<div class="row">&nbsp</div>
		<div class="row mt-4 ml-4">
			{% buttons submit="  Submit  " %} {% endbuttons %}
		</div>
	</div>
		
  </div>


<h2> Data archive</h2>


</div>


</form>
</div>

{% endblock %}

chat/templates/chat/chat_delete_user.html
{% extends "chat/chat_base.html" %}
{% load bootstrap4 %}

{% block title %} Deleting a user {% endblock %}

{% block content %}
<h2> Deleting a user </h2>
<form method="post">
  {% csrf_token %}
  
  {% buttons submit="Delete" %} {% endbuttons %}
</form>

{% endblock %}

chat/templates/chat/chat_edit_proposal.html
{% extends "chat/chat_base.html" %}

{% load static %}
{% load bootstrap4 %}
<head>
{% block title %} Edit proposal {% endblock %}

<link rel= "stylesheet" type= "text/css" href= "{% static 'my_css/chat_style.css' %}">

</head>
{% block content %}
<h2> Edit proposition by feedback </h2>
<div class="conteiner-fluid mb-2 border">
<form name="Edit proposal" method="POST" >
  {% csrf_token %}
  <div class="row mb-2">
    
	<div class="col">
	<div class="row ml-4">
		<div class = "col">
			
			<div class="row ml-4">
				<div class="col">
					<div class="row">
						{{ form.f_model.label_tag }}
					</div>
					<div class="row">
						{{ form.f_model }}
					</div>
				</div>
					
				<div class="col">
					<div class="row ml-4">
						{{ form.f_chat_temp.label_tag }}
					</div>
					<div class="text_field row ml-4">
						{{ form.f_chat_temp }}
					</div>
				</div>
			</div>
			
			<div class="row">&nbsp </div>
			<div class="row">
				<b>{{ form.f_content.label_tag }}</b>
			</div>
			<div class="text_field row ">
				<pre>{{ form.f_content|safe }}</pre>
			</div>
									
			<div class="row">
				<b>{{ form.f_feedback.label_tag }}</b>
			</div>
			<div class="text_field row ">
				<pre>{{ form.f_feedback|safe }}</pre>
			</div>
			
			<div class="row">
				{% buttons submit="  Submit  " %} {% endbuttons %}
			</div>
			
			{% if user.is_superuser %}
			<div class="row">
				{{ form.f_debug_field.label_tag }}
			</div>
			<div class="text_field row">
				<pre>{{ form.f_debug_field|safe }}</pre>
			</div>
			{% endif %}
			
		</div>
	</div>
	</div>
			
	<div class="col mb-2 border">
		<h2> Job archive</h2>
		

		<table border="1" colspan="2" width="100%">
		<tr>
		<th>Job_title </th>
		<th>Delete</th>
		</tr>
		{% for record in jobs %}
		<tr>
		<td><a href="{% url 'chat:my_edit_proposal' id=record.id %}" style="text-decoration:None">{{record.job_title }}</a></td>
	      
		<td align="center"><a href="{% url 'chat:my_del_record_edit' id=record.id %}" style="text-decoration:None">Delete</a></td>
		</tr>
		{% endfor %}  
		</table>
	</div>
  </div>
</form>
</div>

{% endblock %}

chat/templates/chat/chat_gpt_response.html
{% extends "chat/chat_base.html" %}

{% load static %}
{% load bootstrap4 %}
<head>
{% block title %} GPT response {% endblock %}

<link rel= "stylesheet" type= "text/css" href= "{% static 'my_css/chat_style.css' %}">

</head>
{% block content %}
<h2> GPT response </h2>
<div class="conteiner-fluid mb-2 border">
<form name="Chat GPT" method="POST" >
	{% csrf_token %}
	<div class="row mb-2">
    
		<div class="col">
			<div class="row ml-4">
				<div class="col">
				
					<div class="row ml-4">
						<div class="col">
							<div class="row">
								{{ form.f_chat_name.label_tag }}
							</div>
							<div class="row">
								{{ form.f_chat_name }}
							</div>
						</div>
					
						<div class="col">
							<div class="row ml-4">
								{{ form.f_chat_temp.label_tag }}
							</div>
							<div class="text_field row ml-4">
								{{ form.f_chat_temp }}
							</div>
						</div>
					</div>
					
					<div class="row">&nbsp</div>
					<div class="row ml-4">
						{{ form.f_chat_field.label_tag }}
					</div>
					<div class="text_field row ml-4">
						{{ form.f_chat_field|safe }}
					</div>
						
				
					<div class="row">&nbsp</div>
					<div class="row ml-4">
						<div class="row ml-4">
							{{ form.f_company.label_tag }}
							
							
						</div>
						<div class=" row ml-4">
							{{ form.f_company }}
							
						</div>
						
						<div class="row ml-4">
							
							{{ form.f_subject.label_tag }}
							
						</div>
						<div class=" row ml-4">
							
							{{ form.f_subject }}
						</div>
					</div>
					
					<div class="row ml-4">
						{{ form.f_ask_field.label_tag }}
					</div>
					<div class="text_field row ml-4">
						<pre>{{ form.f_ask_field|safe }}</pre>
					</div>
					
					<div class="row mt-4 ml-4">
						{% buttons submit="  Submit  " %} {% endbuttons %}
					</div>
				
					{% if user.is_superuser %}
						<div class="row ml-4">
							{{ form.f_debug_field.label_tag }}
						</div>
						<div class="text_field row ml-4">
							<pre>{{ form.f_debug_field|safe }}</pre>
						</div>
					{% endif %}
				
				</div>
			</div>
		</div>

		<div class="col mb-2 border">
			<h2> Chat archive</h2>
			

			<table border="1" colspan="2" width="100%">
				<col style="width:80%">
				<col style="width:20%">
				<tr>
					<th>Chat name </th>
					<th>Delete</th>
				</tr>
				{% for record in chat_list %}
				<tr>
					<td><a href="{% url 'chat:my_chat_gpt_id' id=record.id %}" style="text-decoration:None">{{record.chat_name }}</a></td>
			  
					<td align="center"><a href="{% url 'chat:my_del_chat' id=record.id %}" style="text-decoration:None">Delete</a></td>
				</tr>
				{% endfor %}  
			</table>
		</div>

	</div>
</form>
</div>

{% endblock %}

chat/templates/chat/chat_logout.html
{% extends "chat/chat_base.html" %}

{% block title %} Logout {% endblock %}

{% block content %}
<h2> Logout </h2>
<p> Logout successful!</p>
{% endblock %}